manifestVersion: subsquid.io/v0.1
name: polkadot-balances
version: 2
description: |-
  The very first squid from manifest
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: polkadot
    cmd: ["node", "lib/processor"]
  api:
    env:
      CHAIN: polkadot
    cmd: ["npx", "squid-graphql-server"]
